# Generated by Django 3.0.5 on 2020-04-22 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('imdbID', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('poster', models.URLField()),
                ('download', models.URLField(null=True)),
                ('watched', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('watched_on', models.DateField(null=True)),
            ],
        ),
    ]
